### ISSUE TITLE
TypeError: this.each is not a function

### ISSUE THREAD

**Issue by akohli74** [quilljs/quill#1261]
**Steps for Reproduction**

1. Include quill.js, quill.core.css, quill.snow.css, quill.bubble.css
2. Introduce markup for quill editor container:

				<div class="standalone-container">
					<div id="snow-container"></div>
				</div>

3. Attach quill to container:

			var quill = new Quill('#snow-container', {
				placeholder: 'Compose an epic...',
				theme: 'snow'
			});

4. Load the page.

**Expected behavior**:

Quill Editor opens without error.

**Actual behavior**:

Receiving TypeError: this.each is not a function:

Uncaught TypeError: this.each is not a function
    at NamedNodeMap.collect (core.js:774)
    at Function.Attributor.keys (quill.js:964)
    at AttributorStore.build (quill.js:1028)
    at new AttributorStore (quill.js:1007)
    at Block.FormatBlot.attach (quill.js:893)
    at Block.ShadowBlot (quill.js:574)
    at Block.ContainerBlot [as constructor] (quill.js:205)
    at Block.FormatBlot [as constructor] (quill.js:880)
    at BlockBlot [as constructor] (quill.js:1462)
    at new Block (quill.js:4480)

**Platforms**:

Windows 7, Chrome 55.0.2883.87 m

**Version**: 1.1.9

**Comment by benbro** [comment]
Can you reproduce it in the [codepen](http://codepen.io/quill/pen/KzZqZx)?

**Comment by akohli74** [comment]
Hey - thanks for the quick response.

What I have discovered is that there is likely an incompatibility with the Prototype JavaScript framework, which is what core.js is in our solution.  We are using Prototype JavaScript framework v1.7.0.0.

When I include this library in the codepen, then yes, I am able to get it to fail:

//cdnjs.cloudflare.com/ajax/libs/prototype/1.7.0.0/prototype.js

I'm not seeing any errors in the console, but I know it's failing because the editor is not being rendered at all.

So, just include the CDN for the JavaScript Prototype framework above, and you will see the editor fails.

Any ideas on how this can be corrected would be most appreciated.  It does seem that there is a context that is not being set correctly, or set at all, because the each function does exist in the Enumerable in which it is called.  However, the context is undefined, and therefore, the this pointer is perhaps not pointing to the right place.  That's my best guess at this point.

**Comment by benbro** [comment]
If this is the same issue you might try to upgrade Prototype version like suggested here:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=7067

This is a Prototype issue which is old and unsupported.
Closing.

**Comment by shuckster** [comment]
You can patch the issue yourself if you like. You just need to look at the first argument (the `thisArg`) to each of these:

    [].find.call
    [].forEach.call
    [].indexOf.call
    [].map.call
    [].reduce.call
    [].slice.call

Prototype was written in a time when all of these weren't really imagined to be used on anything other than an Array, or the Enumerable class that was offered by the library.

Consequently, Prototype's duck-punching expects an .each() to exist on the `thisArg` of all of these methods, which isn't the case for NodeList, classList, and so on, which is what is being used in Quill.

Anyway, to fix the problem, wrap the first argument in an Array.from() like this:

Before:

    var format = [].find.call(input.classList, ...

After:

    var format = [].find.call( Array.from(input.classList), ...

Do that for all instances of the list above.

I've had to do the same thing myself and it seems to work alright so far.

**Comment by shuckster** [comment]
So after updating from 1.2.6 to 1.3.0 it's already a pain in the butt to insert Array.from() everywhere, so I came up with this:

    (function _closure_youShouldReallyMigrateAwayFromPrototypeButUnderstandThatYouMightBeUnderTheCoshToGetItWorkingQuickly( global ) {

        var hasOwn = Object.prototype.hasOwnProperty;
        var duckPunch = {

            _each: function __each( callback, thisArg ) {

                if ( this == null ) { // jshint ignore:line
                    throw new TypeError( 'this is null or not defined' );
                }

                if ( typeof callback !== 'function' ) {
                    throw new TypeError( callback + ' is not a function' );
                }

                var key, value, context,

                    O = Object(this),
                    index = 0;

                if ( 1 < arguments.length ) {
                    context = thisArg;
                }

                for ( key in this ) {
                    if ( hasOwn.call( this, key )) {

                        value = this[ key ];
                        callback.call( context, value, index, O );

                        index += 1;

                    }
                }
            }
        };

        duckPunch.each = Enumerable.each; // jshint ignore:line
        duckPunch.forEach = duckPunch.each;

        // ...

        var duckPunchList = 'NodeList NamedNodeMap DOMTokenList HTMLOptionsCollection HTMLCollection'.split( ' ' );

        duckPunchList.forEach( function _forEach( quack ) {
            Object.extend( global[ quack ].prototype, duckPunch );
        });
        
    }( window ));

Hope it helps someone.

**Comment by u12206050** [comment]
@shuckster Nice fix, although upon adding it quill 'works' but I can not space. I can't seem to insert spaces in between text anywhere within the quill editor. I can paste a space in but from the space bar to quill doesn't seem to work.

**Comment by shuckster** [comment]
I tested the patch with Quill v1.3.0 only, and that's the one I'm sticking with for a while.

Not tried yet with v1.3.3, but I remember I had a few issues with v1.3.2 when that came out. I think I even saw the same space-bar issue, and there were more problems with focus/blur/change events not firing as expected.

I didn't get far enough to determine what the problem was, although the patch here is intrusive enough to be the likely cause. Since v1.3.0 worked great I've simply downgraded until I get round to trying again.

**Comment by u12206050** [comment]
@shuckster Thanks for the advice, I downgraded to 1.3.0, and added your "_closure_youShouldReally..." patch above the quill code. However it still seems that the problem exists. If it helps, I am running quill within Magento 2 admin.

**Comment by shuckster** [comment]
I guess it goes without saying, but do run the patch *after* Prototype is loaded, and before you add your Quill component to the page.

I don't know about the jQuery.hotkeys, but [this commit in v1.3.1](https://github.com/quilljs/quill/commit/d30e36d7a8e32d680b54ed47b40a79b839603fc9) started causing problems for me with jQuery mousedown/up hooks, so I can imagine something similar is going on for the spacebar.

**Comment by u12206050** [comment]
So after debugging a bit I realized there are a lot of other events happening after quill has captured the keydown event, and so as a fix I have added evt.stopPropagation() almost right at the start of the keydown event, since "obviously if you are typing within quill only quill needs to know about it."

Here is the updated keydown listener fn:
```
this.quill.root.addEventListener('keydown', function (evt) {
        if (evt.defaultPrevented) return;
        evt.stopPropagation();
        var which = evt.which || evt.keyCode;
```

**Comment by shuckster** [comment]
Thanks for the tip! I'll try it out next upgrade.

**Comment by tungbt94** [comment]
I create a [pull request](https://github.com/quilljs/quill/pull/3288) to fix this error.
