### ISSUE TITLE
quill.addModule is not a function

### ISSUE THREAD

**Issue by dhowe** [quilljs/quill#2341]
Your [example code here](https://quilljs.com/blog/building-a-custom-module/)(and below) seems to refer to an old API? Doesn't appear to work in version 1.3.6

![image](https://user-images.githubusercontent.com/737638/46528842-57b00280-c8c7-11e8-9ab0-f11025ef61ed.png)

Quill.registerModule() also seems to have been replaced by Quill.register()

```js

var Counter = function(quill, options) {
  this.quill = quill;
  this.options = options;
  this.container = document.querySelector(options.container);
  quill.on('text-change', this.update.bind(this));
  this.update();  // Account for initial contents
};

Counter.prototype.calculate = function() {
  var text = this.quill.getText();
  if (this.options.unit === 'word') {
    text = text.trim();
    // Splitting empty text returns a non-empty array
    return text.length > 0 ? text.split(/\s+/).length : 0;
  } else {
    return text.length;
  }
};

Counter.prototype.update = function() {
  var length = this.calculate();
  var label = this.options.unit;
  if (length !== 1) {
    label += 's';
  }
  this.container.innerHTML = length + ' ' + label;
}

Quill.registerModule('counter', Counter);

var quill = new Quill('#editor');
var counter = quill.addModule('counter', {
  container: '#counter',
  unit: 'word'
});
