### ISSUE TITLE
Regression Quill 2.0.0 ( Quill.register)

### ISSUE THREAD

**Issue by Didi3333** [quilljs/quill#4133]
With ReactJS On Version 2.0.0 Quill.register is not a function

That works with Quill 2.0.0-dev.4 

To reproduce, i have created two codesanbox :

Quill 2.0.0-dev.4: (Version that works)
https://codesandbox.io/p/sandbox/quill-2-0-0-dev-4-w2sfmd

Quill 2.0.0 (Version with error)
https://codesandbox.io/p/sandbox/quill-2-0-0-33qn9p

**Comment by ludejun** [comment]
[quill-react-commercial](https://github.com/ludejun/quill-react-commercial) use the latest quill@2.0.1.
