### ISSUE TITLE
Angular AOT build fails with Cannot find name 'Quill'.

### ISSUE THREAD

**Issue by PW999** [quilljs/quill#1879]
I'm trying to write a custom blot for Quill so that I can add HTML5 video and audio tags to the editor. The code I now have works fine in development but the angular AOT build fails.

**Steps for Reproduction**
```
...
import { Component, EventEmitter, Input, Output, ViewChild } from "@angular/core";
import { GlobalService } from "../../service/global.service";
...
    let BlockEmbed = Quill.import('blots/block/embed');
    let Inline = Quill.import('blots/inline');
    let Block = Quill.import('blots/block');
    class VideoBlot extends BlockEmbed {

        static create(value) {
            this.cache = {};
            let node = super.create();
            node.setAttribute('controls', '');
            node.setAttribute('controlsList', 'nodownload');
            node.setAttribute('style', 'max-width:720px');
            node.setAttribute('player-source', value.src);
            let src = document.createElement('source');
            src.setAttribute('src', value.src);
            node.appendChild(src);
            this.cache.length = 1;//94 + value.src.length;
            return node;
        }

        deleteAt(index: number, length: number) {
            super.deleteAt(0, 1);
        }

        length() {
            return 2;
        }

        static value(node) {
            return {
                controls: node.getAttribute('controls'),
                controlsList: node.getAttribute('controlsList'),
                style: node.getAttribute('max-width:720px'),
                src: node.getAttribute('player-source')
            };
        }
    }
    VideoBlot.blotName = 'clbvideo';
    VideoBlot.tagName = 'video';
    Quill.register(VideoBlot);
```

Adding the video blot to the editor is done as follows
```
this.quill.insertEmbed(this.range.index + 1, 'clbvideo', {
                src: this.urlText
            }, "user");
```

our tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["dom","es2015"],
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "types": [
      "core-js"
    ]

  },

  "angularCompilerOptions": {
    "genDir": "aot/",
    "skipMetadataEmit" : true
  }
}
```

our webpack config
```
var webpack = require("webpack");
var helpers = require('./config/helpers');
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CompressionPlugin = require("compression-webpack-plugin");
var ngtools = require('@ngtools/webpack');
const extractSass = new ExtractTextPlugin({
    filename: "./scssStyles.css"
});

module.exports = {
    entry: {
        'polyfills': './app/polyfills.js',
        'vendor': './app/vendor.ts',
        'app': './app/main-aot.ts'
    },

    output: {
        path: helpers.root('prod'),
        filename: "./[name].js"
    },

    resolve: {
        extensions: ['.ts', '.js']
    },


    module: {
        rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file-loader?name=./assets/[name].[ext]'
            },
            {
                test: /\.ts$/,
                loaders: '@ngtools/webpack'
            },
            {
                test: /\.html$/,
                loader: 'raw-loader'
            },
            {
                include: /\.json$/,
                loaders: ["json-loader"]
            }
        ],

    },

    plugins: [

        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),

        new ngtools.AotPlugin({
            tsConfigPath: helpers.root('./tsconfig.aot.json'),
            entryModule: helpers.root('./app/app.module.ts#AppModule')
        }),

        new ExtractTextPlugin("./styles.css"),
        extractSass,

        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        })
    ]
};

```

**Expected behavior**:
Angular AOT build using @ngtools/webpack works.

**Actual behavior**:
Errors during build

> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (31,26): Cannot find name 'Quill'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (32,22): Cannot find name 'Quill'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (33,21): Cannot find name 'Quill'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (37,22): Property 'cache' does not exist on type 'typeof VideoBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (46,22): Property 'cache' does not exist on type 'typeof VideoBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (67,19): Property 'blotName' does not exist on type 'typeof VideoBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (68,19): Property 'tagName' does not exist on type 'typeof VideoBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (73,22): Property 'cache' does not exist on type 'typeof AudioBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (82,22): Property 'cache' does not exist on type 'typeof AudioBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (103,19): Property 'blotName' does not exist on type 'typeof AudioBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (104,19): Property 'tagName' does not exist on type 'typeof AudioBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (121,20): Property 'blotName' does not exist on type 'typeof SourceBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (122,20): Property 'tagName' does not exist on type 'typeof SourceBlot'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (125,9): Cannot find name 'Quill'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (126,9): Cannot find name 'Quill'.
> 
> ERROR in /workspace/workspace/my-app/app/view/common/quillComponent.ts (127,9): Cannot find name 'Quill'.

**Platforms**:

Build on Linux Mint 18.3
npm 5.0.3
node 6.9.0

**Version**:

This is the version we use, also tried it with the latest version and it didn't work either.
```
"quill": {
  "version": "1.3.2",
  "resolved": "https://registry.npmjs.org/quill/-/quill-1.3.2.tgz",
  "integrity": "sha512-Tudr3tPSPr64J+Fnr8hsNKbi5e2xueyLROmemOIsIsUIeX+WU7LtA22HWRRHr2gGasqxhah2NzFGe9N32eJkMg==",
  "requires": {
    "clone": "2.1.1",
    "deep-equal": "1.0.1",
    "eventemitter3": "2.0.3",
    "extend": "3.0.1",
    "parchment": "1.1.0",
    "quill-delta": "3.6.1"
  },
  "dependencies": {
    "quill-delta": {
      "version": "3.6.1",
      "resolved": "https://registry.npmjs.org/quill-delta/-/quill-delta-3.6.1.tgz",
      "integrity": "sha512-jSD448mqyDevX0FhdjNppMLHl67vXEzZEDjQrtkfDXI6s6e3WJkJOZpYiVhqxLl4HcYNeAhFT+fhAeX8ef7Cew==",
      "requires": {
        "deep-equal": "1.0.1",
        "extend": "3.0.1",
        "fast-diff": "1.1.1"
      }
    }
  }
},


"@types/quill": {
  "version": "0.0.31",
  "resolved": "https://registry.npmjs.org/@types/quill/-/quill-0.0.31.tgz",
  "integrity": "sha512-2Y0Pr5SSNf7kpD4mWMPSYYYyVTLbBNn99DtEYzZ1hlEry1fiWCJYLTYSoGTgPvYiRU4JNRi9LYW0EOV60jN9yA=="
},
```

FYI: this is a cross-post of my question on [SO](https://stackoverflow.com/questions/47776674/custom-video-blot-for-quill).

**Comment by derekaug** [comment]
I don't see where you are importing Quill. You may want to try importing Quill from the dist folder.

`import Quill from 'quill/dist/quill';`

**Comment by PW999** [comment]
When I import Quill like that, in the non-AOT build it doesn't work and I had to change the following lines so that BlockEmbed and Inline are explicitely defined as 'any'. 
```
        let BlockEmbed : any = Quill.import('blots/block/embed');
        let Inline : any = Quill.import('blots/inline');
```

However, this causes the following exception when running the code

> ERROR Error: [Parchment] Unable to create clbvideo blot
>     at new e (registry.ts:18)
>     at Object.r [as create] (registry.ts:49)
>     at e.insertAt (block.ts:52)
>     at e.value (block.js:84)
>     at e.insertAt (container.ts:93)
>     at e.insertAt (scroll.ts:55)
>     at e.value (scroll.js:95)
>     at t.value (editor.js:153)
>     at quill.js:259
>     at t.a (quill.js:437)

I do get a lot of warnings like this when running the code

> quill Overwriting formats/clbvideo with ƒ VideoBlot(){return null!==e&&e.apply(this,arguments)||this}
> debug @ app.js:1
> app.js:1 quill Overwriting formats/clbaudio with ƒ AudioBlot(){return null!==e&&e.apply(this,arguments)||this}
> debug @ app.js:1
> app.js:1 quill Overwriting formats/clbsrc with ƒ SourceBlot(){return null!==e&&e.apply(this,arguments)||this}



Maybe some additional info. The blots are registered in the constructor of our QuillComponent. 

The editor init event is consumed by this method
```
    editorInit(event) {
        this.quill = event.editor;
    }
```

and adding the video is done by calling:
```
this.quill.insertEmbed(this.range.index + 1, 'clbvideo', {
                src: this.urlText
            }, "user");
```

where this.quill is the same quill instance as initialized by the editorInit method.

**Comment by PW999** [comment]
Maybe interesting to add is that I'm using the primeng editor.

**Comment by PW999** [comment]
I think I managed to fix it by looking the the primeng source code. I did not need to explicitely import Quill but simply add 
`declare var Quill: any;`

to the source (as per https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts)

Now both the non-AOT and AOT build work and I can now add HTML5 video and audio tags to the editor.
